Meteor.methods({
	AddQuizz:function(obj){
		quizz.insert(obj);
	},
	UpdateQuizz:function(id,obj){
		quizz.update({_id:id},{$set:obj});
	},
	deleteqa:function(id){
		quizz.remove({_id:id});
	},
	AddAnswerQuizz:function(obj){
		answerquizz.insert(obj);
	}
});